CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_username_unique UNIQUE (username)
);

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_status VARCHAR(255) NOT NULL,
    area DOUBLE PRECISION,
    bathrooms INTEGER,
    bedrooms INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    location VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    property_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT properties_approval_status_check
        CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT properties_property_type_check
        CHECK (property_type IN ('APARTMENT', 'HOUSE', 'CONDO', 'LAND', 'TOWNHOUSE')),
    CONSTRAINT properties_status_check
        CHECK (status IN ('FOR_SALE', 'FOR_RENT')),
    CONSTRAINT properties_owner_fk
        FOREIGN KEY (owner_id) REFERENCES users (id)
);
