ALTER TABLE properties
    ADD COLUMN IF NOT EXISTS parking INTEGER,
    ADD COLUMN IF NOT EXISTS year_built INTEGER,
    ADD COLUMN IF NOT EXISTS ownership_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS street_address VARCHAR(500),
    ADD COLUMN IF NOT EXISTS township VARCHAR(100),
    ADD COLUMN IF NOT EXISTS city VARCHAR(100),
    ADD COLUMN IF NOT EXISTS state_region VARCHAR(100),
    ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS has_grant BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS has_permit BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS property_features (
    property_id BIGINT NOT NULL,
    feature VARCHAR(100) NOT NULL,
    CONSTRAINT property_features_pkey PRIMARY KEY (property_id, feature),
    CONSTRAINT property_features_property_fk
        FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
