import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    favorites: 'Favorites',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    signOut: 'Sign Out',
    dashboard: 'Dashboard',
    addProperty: 'Add Property',
    adminPanel: 'Admin Panel',
    
    // Home Page
    activeListings: 'active listings nationwide',
    heroTitle: 'Find Your Perfect Home, Smarter.',
    heroSubtitle: 'Search millions of listings with intelligent filters, instant alerts, and verified agents — all in one place.',
    buy: 'Buy',
    rent: 'Rent',
    searchLocation: 'City, neighborhood, or ZIP code',
    searchHomes: 'Search Homes',
    activeListingsCount: 'Active Listings',
    citiesCovered: 'Cities Covered',
    happyBuyers: 'Happy Buyers',
    agentPartners: 'Agent Partners',
    handPicked: 'Hand-Picked',
    featuredProperties: 'Featured Properties',
    viewAllListings: 'View all listings',
    beds: 'beds',
    baths: 'baths',
    sqft: 'sqft',
    viewDetails: 'View Details',
    whyChooseUs: 'Why UrbanNest',
    featuresTitle: 'Everything you need to find home',
    smartSearch: 'Smart Search',
    smartSearchDesc: 'AI-powered filters match your lifestyle preferences with the right home.',
    virtualTours: 'Virtual Tours',
    virtualToursDesc: 'Explore every room in 3D from your device before scheduling a visit.',
    instantAlerts: 'Instant Alerts',
    instantAlertsDesc: 'Get notified the moment a home matching your criteria hits the market.',
    secureTransactions: 'Secure Transactions',
    secureTransactionsDesc: 'Encrypted documents and verified agents for a trusted buying experience.',
    readyToList: 'Ready to list your property?',
    readyToListDesc: 'Join 3,200+ agents and sellers using UrbanNest to connect with qualified buyers nationwide.',
    createFreeAccount: 'Create Free Account',
    browseListings: 'Browse Listings',
    
    // Auth
    signInTo: 'Sign in to UrbanNest',
    dontHaveAccount: "Don't have an account?",
    createOneFree: 'Create one free',
    orContinueWith: 'or continue with email',
    emailAddress: 'Email address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me for 30 days',
    termsAndPrivacy: 'By signing in, you agree to our',
    terms: 'Terms',
    and: 'and',
    privacyPolicy: 'Privacy Policy.',
    quickDemoLogin: 'Quick demo login',
    createYourAccount: 'Create your account',
    alreadyHaveOne: 'Already have one?',
    iWantToBuyRent: 'I Want To Buy/Rent',
    iWantToSellList: 'I Want To Sell/List',
    firstName: 'First name',
    lastName: 'Last name',
    confirmPassword: 'Confirm password',
    minChars: 'Min. 8 characters',
    repeatPassword: 'Repeat password',
    agreeTo: "I agree to UrbanNest's",
    termsOfService: 'Terms of Service',
    privacyPolicyLink: 'Privacy Policy.',
    createAccount: 'Create Account',
    
    // Dashboard
    totalPosted: 'Total Posted',
    activeListingsTab: 'Active Listings',
    pending: 'Pending',
    rejected: 'Rejected',
    myProperties: 'My Properties',
    savedFavorites: 'Saved Favorites',
    noProperties: 'No properties yet',
    addFirstProperty: 'Add Your First Property',
    noFavorites: 'No saved favorites yet',
    browseProperties: 'Browse Properties',
    
    // Property Details
    listedBy: 'Listed by',
    verifiedAgent: 'Verified Agent',
    scheduleViewing: 'Schedule a Viewing',
    mortgageEstimate: 'Mortgage Estimate',
    mortgageSubtitle: '30-yr fixed at 6.8% APR, 20% down',
    perMonth: '/month',
    estimateDisclaimer: '* Estimate only. Contact a lender for exact terms.',
    shareThisProperty: 'Share this property',
    copyLink: 'Copy link',
    email: 'Email',
    save: 'Save',
    aboutThisProperty: 'About this property',
    similarProperties: 'Similar Properties',
    overview: 'Overview',
    features: 'Features',
    contact: 'Contact',
    built: 'Built',
    area: 'Area',
    parking: 'Parking',
    cars: 'cars',
    contactOwner: 'Contact Owner',
    callOwner: 'Call Owner',
    chatOnViber: 'Chat on Viber',
    
    // Add Property
    addNewProperty: 'Add New Property',
    editProperty: 'Edit Property',
    fillDetails: 'Fill in the details to list your property',
    propertyInfo: 'Property Info',
    basicDetails: 'Basic property details',
    specifications: 'Specifications',
    sizeAndLayout: 'Size and layout',
    description: 'Description',
    tellUsMore: 'Tell us more',
    media: 'Media',
    uploadPhotos: 'Upload photos',
    propertyTitle: 'Property Title',
    listingType: 'Listing Type',
    forSale: 'For Sale',
    forRent: 'For Rent',
    price: 'Price (MMK)',
    township: 'Township',
    selectLocation: 'Select location',
    sqftLabel: 'Sq Ft',
    address: 'Address',
    fullAddress: 'Full property address',
    descriptionLabel: 'Description',
    descPlaceholder: 'Describe your property in detail...',
    featuresLabel: 'Features & Amenities',
    dragDrop: 'Drag and drop your photos here',
    orClickToBrowse: 'or click to browse',
    chooseFiles: 'Choose Files',
    uploadAtLeast: 'Upload at least 1 photo. Recommended size: 1200x800px',
    previous: 'Previous',
    next: 'Next',
    submitForApproval: 'Submit for Approval',
    propertySubmitted: 'Property Submitted!',
    submittedDesc: 'Your property has been submitted for approval.',
    redirecting: 'Redirecting to dashboard...',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    totalProperties: 'Total Properties',
    pendingApprovals: 'Pending Approvals',
    manageData: 'Manage Data',
    approve: 'Approve',
    reject: 'Reject',
    
    // Footer
    explore: 'Explore',
    sellers: 'Sellers',
    company: 'Company',
    buyAHome: 'Buy a Home',
    rentAHome: 'Rent a Home',
    newListings: 'New Listings',
    priceTrends: 'Price Trends',
    listAProperty: 'List a Property',
    agentTools: 'Agent Tools',
    marketAnalysis: 'Market Analysis',
    pricingGuide: 'Pricing Guide',
    aboutUs: 'About Us',
    careers: 'Careers',
    press: 'Press',
    contact: 'Contact',
    footerDesc: 'Your trusted partner in finding and managing real estate.',
    copyright: '© 2026 UrbanNest, Inc. All rights reserved.',
    privacy: 'Privacy',
    termsLink: 'Terms',
    cookies: 'Cookies',
  },
  my: {
    // Navigation
    home: 'အိမ်',
    favorites: 'ကြိုက်နှစ်သက်',
    signIn: 'ဝင်ရောက်',
    getStarted: 'စတင်',
    signOut: 'ထွက်',
    dashboard: 'ဒက်ရှ်ဘုတ်',
    addProperty: 'အိမ်ထည့်',
    adminPanel: 'Admin Panel',
    
    // Home Page
    activeListings: 'တိုင်းဒေသကြီးတစ်ဝိုက် အိမ်ခြံမြေ စာရင်းများ',
    heroTitle: 'သင့်အိမ်အကောင်းဆုံးကို ပိုမိုလွယ်ကူစွာ ရှာဖွေပါ။',
    heroSubtitle: 'ဉာဏ်ရည်တု စစ်ထုတ်မှုများ၊ ချက်ချင်း သတိပေးချက်များနှင့် အတည်ပြုထားသော အေဂျင့်များဖြင့် စာရင်းပေါင်းများစွာကို ရှာဖွေပါ။',
    buy: 'ဝယ်',
    rent: 'ငှား',
    searchLocation: 'မြို့နယ်၊ ရပ်ကွက် သို့မဟုတ် ZIP code',
    searchHomes: 'အိမ်များ ရှာဖွေပါ',
    activeListingsCount: 'လက်ရှိ စာရင်း',
    citiesCovered: 'မြို့ပေါင်း',
    happyBuyers: 'ပျော်ရွှင်သော ဝယ်ယူသူများ',
    agentPartners: 'Agent ပူးပေါင်းဆောင်ရွက်သူများ',
    handPicked: 'ရွေးချယ်ထားသည်',
    featuredProperties: 'အထူးချွတ် အိမ်ခြံမြေများ',
    viewAllListings: 'စာရင်းအားလုံးကြည့်ရန်',
    beds: 'အိပ်ခန်း',
    baths: 'ရေချိုခန်း',
    sqft: 'စတုရန်းပေ',
    viewDetails: 'အသေးစိတ်ကြည့်ရန်',
    whyChooseUs: 'ဘာကြောင့် UrbanNest ကို ရွေးချယ်သင့်သလဲ',
    featuresTitle: 'သင့်အိမ်အကောင်းဆုံးကို ရှာဖွေရန် လိုအပ်သမျှ',
    smartSearch: 'ဉာဏ်ရည်တု ရှာဖွေမှု',
    smartSearchDesc: 'AI-powered filters ဖြင့် သင့်လိုအပ်ချက်များနှင့် ကိုက်ညီသော အိမ်ကို ရှာဖွေပါ။',
    virtualTours: 'Virtual Tours',
    virtualToursDesc: ' visit ချိတ်ဆက်မတိုင်မီ 3D ဖြင့် အခန်းတိုင်းကို ကြည့်ရှုပါ။',
    instantAlerts: 'ချက်ချင်း သတိပေးချက်',
    instantAlertsDesc: 'သင့်စံနှုန်းနှင့် ကိုက်ညီသော အိမ် စျေးကွက်ထဲ ရောက်ရှိသည်နှင့် ချက်ချင်း သိရှိပါ။',
    secureTransactions: 'လုံခြုံသော ငွေပေးချေမှု',
    secureTransactionsDesc: 'ယုံကြည်စိတ်ချရသော ဝယ်ယူမှု အတွေ့အကြုံအတွက် ကုဒ်ဝှက်ထားသည့် စာရွက်စာတမ်းများနှင့် အတည်ပြုထားသည့် Agent များ။',
    readyToList: 'သင့်အိမ်ကို စာရင်းတင်လိုပါသလား?',
    readyToListDesc: 'တိုင်းဒေသကြီးတစ်ဝိုက်မှ ဝယ်ယူသူများနှင့် ချိတ်ဆက်ရန် UrbanNest ကို အသုံးပြုသည့် Agent ၃,၂၀၀+ နှင့် ပူးပေါင်းဆောင်ရွက်ပါ။',
    createFreeAccount: 'အခမဲ့ အကောင့်ဖွင့်ပါ',
    browseListings: 'စာရင်းများကြည့်ရန်',
    
    // Auth
    signInTo: 'UrbanNest သို့ ဝင်ရောက်ပါ',
    dontHaveAccount: 'အကောင့် မရှိသေးပါလား?',
    createOneFree: 'အခမဲ့ ဖန်တီးပါ',
    orContinueWith: 'သို့မဟုတ် email ဖြင့် ဆက်လက်ပါ',
    emailAddress: 'အီးမေးလ်',
    password: 'စကားဝှက်',
    forgotPassword: 'စကားဝှက် မေ့နေပါသလား?',
    rememberMe: 'ရက် ၃၀ အတွက် မှတ်ထားပါ',
    termsAndPrivacy: 'ဝင်ရောက်ခြင်းဖြင့် သင်သည်',
    terms: 'စည်းမျဉ်းများ',
    and: 'နှင့်',
    privacyPolicy: 'ကိုယ်ရေးမူဝါဒကို သဘောတူပါသည်။',
    quickDemoLogin: 'အမြန် demo ဝင်ရောက်မှု',
    createYourAccount: 'သင့်အကောင့်ကို ဖန်တီးပါ',
    alreadyHaveOne: 'ရှိပြီးသားလား?',
    iWantToBuyRent: 'ဝယ်/ငှား လိုပါသည်',
    iWantToSellList: 'ရောင်း/စာရင်းတင် လိုပါသည်',
    firstName: 'နာမည်',
    lastName: 'အမည်နောက်ဆက်တွဲ',
    confirmPassword: 'စကားဝှက် အတည်ပြုပါ',
    minChars: 'အနည်းဆုံး စာလုံး ၈ လုံး',
    repeatPassword: 'စကားဝှက် ထပ်ရေးပါ',
    agreeTo: 'UrbanNest ၏',
    termsOfService: 'ဝန်ဆောင်မှု စည်းမျဉ်းများ',
    privacyPolicyLink: 'ကိုယ်ရေးမူဝါဒကို သဘောတူပါသည်။',
    createAccount: 'အကောင့်ဖန်တီးပါ',
    
    // Dashboard
    totalPosted: 'စုစုပေါင်း တင်ထားသည်',
    activeListingsTab: 'လက်ရှိ စာရင်း',
    pending: 'စောင့်ဆိုင်းနေသည်',
    rejected: 'ငြင်းဆိုထားသည်',
    myProperties: 'ကျွန်ုပ်၏ အိမ်ခြံမြေများ',
    savedFavorites: 'သိမ်းဆည်းထားသည်',
    noProperties: 'အိမ်ခြံမြေ မရှိသေးပါ',
    addFirstProperty: 'သင့်ပထမဆုံး အိမ်ခြံမြေကို ထည့်ပါ',
    noFavorites: 'သိမ်းဆည်းထားခြင်း မရှိသေးပါ',
    browseProperties: 'အိမ်ခြံမြေများ ကြည့်ရန်',
    
    // Property Details
    listedBy: 'စာရင်းတင်သူ',
    verifiedAgent: 'အတည်ပြုထားသည့် Agent',
    scheduleViewing: 'ကြည့်ရန် ချိတ်ဆက်ပါ',
    mortgageEstimate: 'အိမ်ခြံမြေ ချေးငွေ ခန့်မှန်းချက်',
    mortgageSubtitle: '၃၀-နှစ် ရည်မှန်းချက် ၆.၈% APR၊ ၂၀% ဖြည့်',
    perMonth: '/လ',
    estimateDisclaimer: '* ခန့်မှန်းချက်သာ။ တိကျသည့် စည်းကမ်းချက်များအတွက် ချေးငွေလက်ခံသူကို ဆက်သွယ်ပါ။',
    shareThisProperty: 'ဤအိမ်ခြံမြေကို မျှဝေပါ',
    copyLink: 'လင့်ခ် ကူးယူပါ',
    email: 'အီးမေးလ်',
    save: 'သိမ်းဆည်းပါ',
    aboutThisProperty: 'ဤအိမ်ခြံမြေအကြောင်း',
    similarProperties: 'ဆင်တူသည့် အိမ်ခြံမြေများ',
    overview: 'အနှစ်ချုပ်',
    features: 'လုပ်ဆောင်ချက်များ',
    contact: 'ဆက်သွယ်ရန်',
    built: 'ဆောက်လုပ်ပြီး',
    area: 'ဧရိယာ',
    parking: 'ကားရပ်နားရန်',
    cars: 'ကား',
    contactOwner: 'ပိုင်ရှင်ကို ဆက်သွယ်ပါ',
    callOwner: 'ပိုင်ရှင်ကို ဖုန်းခေါ်ပါ',
    chatOnViber: 'Viber တွင် စကားပြောပါ',
    
    // Add Property
    addNewProperty: 'အိမ်ခြံမြေအသစ် ထည့်ပါ',
    editProperty: 'အိမ်ခြံမြေ ပြင်ဆင်ပါ',
    fillDetails: 'သင့်အိမ်ခြံမြေကို စာရင်းတင်ရန် အသေးစိတ်ဖြည့်ပါ',
    propertyInfo: 'အိမ်ခြံမြေ အချက်အလက်',
    basicDetails: 'အခြေခံ အသေးစိတ်',
    specifications: 'သတ်မှတ်ချက်များ',
    sizeAndLayout: 'အရွယ်အစားနှင့် အပြင်အဆင်',
    description: 'ဖော်ပြချက်',
    tellUsMore: 'ပိုမိုပြောပြပါ',
    media: 'မီဒီယာ',
    uploadPhotos: 'ဓာတ်ပုံများ တင်ပါ',
    propertyTitle: 'အိမ်ခြံမြေ ခေါင်းစဉ်',
    listingType: 'စာရင်းအမျိုးအစား',
    forSale: 'ရောင်းရန်',
    forRent: 'ငှားရန်',
    price: 'စျေးနှုန်း (MMK)',
    township: 'မြို့နယ်',
    selectLocation: 'တည်နေရာ ရွေးပါ',
    sqftLabel: 'စတုရန်းပေ',
    address: 'လိပ်စာ',
    fullAddress: 'အိမ်ခြံမြေ လိပ်စာ အပြည့်အစုံ',
    descriptionLabel: 'ဖော်ပြချက်',
    descPlaceholder: 'သင့်အိမ်ခြံမြေကို အသေးစိတ် ဖော်ပြပါ...',
    featuresLabel: 'လုပ်ဆောင်ချက်များနှင့် အဆင်ပြေမှုများ',
    dragDrop: 'သင့်ဓာတ်ပုံများကို ဒီမှာ ဆွဲထည့်ပါ',
    orClickToBrowse: 'သို့မဟုတ် ကြည့်ရန် နှိပ်ပါ',
    chooseFiles: 'ဖိုင်များ ရွေးပါ',
    uploadAtLeast: 'အနည်းဆုံး ဓာတ်ပုံ ၁ ပုံ တင်ပါ။ အကြံပြုအရွယ်အစား- 1200x800px',
    previous: 'နောက်သို့',
    next: 'ရှေ့သို့',
    submitForApproval: 'အတည်ပြုချက်အတွက် တင်သွင်းပါ',
    propertySubmitted: 'အိမ်ခြံမြေ တင်သွင်းပြီးပါပြီ!',
    submittedDesc: 'သင့်အိမ်ခြံမြေကို အတည်ပြုချက်အတွက် တင်သွင်းပြီးပါပြီ။',
    redirecting: 'ဒက်ရှ်ဘုတ်သို့ ပြန်ညွှန်နေပါသည်...',
    
    // Admin
    adminDashboard: 'Admin ဒက်ရှ်ဘုတ်',
    totalUsers: 'စုစုပေါင်း အသုံးပြုသူ',
    totalProperties: 'စုစုပေါင်း အိမ်ခြံမြေ',
    pendingApprovals: 'စောင့်ဆိုင်းနေသည့် အတည်ပြုချက်',
    manageData: 'ဒေတာ စီမံပါ',
    approve: 'အတည်ပြုပါ',
    reject: 'ငြင်းဆိုပါ',
    
    // Footer
    explore: 'ရှာဖွေရန်',
    sellers: 'ရောင်းချသူများ',
    company: 'ကုမ္ပဏီ',
    buyAHome: 'အိမ်ဝယ်ရန်',
    rentAHome: 'အိမ်ငှားရန်',
    newListings: 'စာရင်းအသစ်များ',
    priceTrends: 'စျေးနှုန်း ခန့်မှန်းချက်',
    listAProperty: 'အိမ်ခြံမြေ စာရင်းတင်ရန်',
    agentTools: 'Agent ကိရိယာများ',
    marketAnalysis: 'စျေးကွက် ခွဲခြမ်းစိတ်ဖြာချက်',
    pricingGuide: 'စျေးနှုန်း လမ်းညွှန်',
    aboutUs: 'ကျွန်ုပ်တို့အကြောင်း',
    careers: 'အလုပ်အကိုင်',
    press: 'သတင်းစာ',
    contact: 'ဆက်သွယ်ရန်',
    footerDesc: 'အိမ်ခြံမြေ ရှာဖွေခြင်းနှင့် စီမံခြင်းတွင် သင့်ယုံကြည်ရသည့် ပူးဖောင်းပါ။',
    copyright: '© ၂၀၂၆ UrbanNest, Inc. မူပိုင်ခွင့် အားလုံး ထိန်းသိမ်းထားသည်။',
    privacy: 'ကိုယ်ရေးမူဝါဒ',
    termsLink: 'စည်းမျဉ်း',
    cookies: 'Cookie များ',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('urbannest-language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('urbannest-language', language);
    document.documentElement.lang = language === 'my' ? 'my' : 'en';
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'my' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}